### PR TITLE
During watch reset don't skip added events where backend data has changed

### LINKED ISSUE #1017: [BUG] Flannel broken watches
Gravity Version: 5.0.x -> 7.0.x

This has been observed more than once now, that flannel is able to miss events from other members of the cluster due to a failure in the etcd watches, that can be triggered specifically by a node reboot. I missed capturing the specific log in the watch failure, but effectively the watch get's disconnected, events are processed by the cluster that change some flannel state within etcd, the watch is detected as broken and re-created, but the re-creation of the watch generates an error that the last seen index is too old, and the watch is re-created from the most recent revision.

This can cause the client to miss events, because what it should do is flush/re-sync all state when the watch isn't able to be resumed from it's old index position. 

The likely solution is the flannel should flush and re-sync all internal state when resuming a watch fails and the watch itself is re-created.

### PR DESCRIPTION
**Pull request by knisbet**
Fixes https://github.com/gravitational/gravity/issues/1017

This updates the flannel logic to also consider BackendData changes when resetting the leaseWatcher due to an etcd watch where the index is outside of the history window. When a node is rebooted when the watch is being reset, the current logic appears to only consider whether the subnet lease itself exists, and not if any of the data has changed. In our case, the node reboot resets the VtepMac of the node, which is stored in the BackendData field.

### CODE REVIEW

**Review by a-palchikov — APPROVED** [review]
lgtm although I'd consider tucking the condition into a readable function like:
```go
func shouldResetLease(oldLease, newLease Lease) bool
```

File: subnet/watch.go [hunk 1]
```diff
@@ -76,7 +77,7 @@ func (lw *leaseWatcher) reset(leases []Lease) []Event {
 
 		found := false
 		for i, ol := range lw.leases {
-			if ol.Subnet.Equal(nl.Subnet) {
+			if ol.Subnet.Equal(nl.Subnet) && bytes.Compare(ol.Attrs.BackendData, nl.Attrs.BackendData) == 0 {
```
Comment (r0mant) [inline subnet/watch.go:80]: Just a thought, I think BackendData is a JSON object, right? So since we use byte compare this condition can also potentially trigger if the backend data marshaled differently for "ol" and "nl" as the marshaled field order may not be guaranteed. Probably not a big deal if the object contains just a single field (VtepMAC) most of the time.

**Review by r0mant — APPROVED** [review]

File: subnet/watch.go (hunk 1 above)
Comment (knisbet) [reply subnet/watch.go:80]: I suspect a change in the field order would indicate that there has been a write to the object in etcd, which we likely don't want to suppress passing that change to the backend when re-creating the watch anyways. So it's a good point, but I think in this case the bytes.Compare reinforces the expected behaviour of passing along any change notification from etcd to the backend.
